#video conversion settings
nice_level:     '19'
ffmpeg:         '/opt/local/bin/ffmpeg'
ffmpeg_options: -y -t 00:01:00 -threads 4 -croptop 6 -cropbottom 6 -cropleft 6 -cropright 6 -s 640x480 -aspect 640:480 -r 29.97 -vcodec libx264 -g 150 -qmin 25 -qmax 51 -b 1000k -maxrate 1450k -level 30 -loop 1 -sc_threshold 40 -refs 2 -keyint_min 40 -partp4x4 1 -rc_eq 'blurCplx^(1-qComp)' -deinterlace -async 50 -acodec libfaac -ar 48000 -ac 2 -ab 128k -f mp4
qtfaststart:    '/Users/cjmartin/bin/qt-faststart'
atomicparsley:  '/Users/cjmartin/bin/AtomicParsley'

#upload settings (your mythtv user must have an authorized no passphrase key on the upload_host)
#later this would be something like "PVArchive username/pass"
scp:            '/usr/bin/scp'
upload_user:    'you'
upload_host:    'yourhugeonlinestoreage.com'
upload_path:    '/where/you/want/to/save/the/vids/'

#mythconverg database connection
host:           'localhost'
database:       'mythconverg'
username:       'mythtv'
password:       'find your password in /usr/share/mythtv/mysql.txt'